name: Deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: pull-test-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd app
            git pull origin master
            go test -v ./businesses/...
            docker-compose down && docker-compose up --build -d
